#!/bin/sh

for F in "$@"
do
	if [ ! -f $F ] && [ ! -d $F ]; then
		echo "$F not found";
		continue;
	fi
	OLD="$F.old"
	if [ -f $OLD ] || [ -d $OLD ]; then 
		$0 "$OLD"
	fi
	echo "copying $F to $OLD"
	cp -rp $F $OLD
done
