#!/bin/sh
extensions=("old" "OLD" "back" "back" "backup" "BAK" "cpy" "copy" "other" "OK")

for F in "$@"
do
	if [ ! -f $F ] && [ ! -d $F ]; then
		echo "$F not found";
		continue;
	fi

	# Seed random generator
	RANDOM=$$$(date +%s)
	extension=${extensions[$RANDOM % ${#extensions[@]} ]}

	OLD="$F.$extension"
	if [ -f $OLD ] || [ -d $OLD ]; then
		$0 "$OLD"
	fi
	echo "copying $F to $OLD"
	cp -rp $F $OLD
done
